export class settingsConstansts {
  public static settingskeys = {
    profile: 'Profile',
    mapConfiguration: 'Map',
    privileges: 'Privileges',
    configurations: 'Configurations',
    dropdown:'Reference List',
    security : 'Application Settings',
    emailTemplate: 'Email Template',
    account: 'accountId',
    mapSelect: 'mapType',
    accountLabel: 'Account',
    mapLabel: 'Map',
    mapTitle: 'Map Configuration',
    configTitle:'Configuration',
    accountSettings:'Account Settings',
    maps: [{ id: 'osm', name: 'Open Street Maps' }, { id: 'mapBox', name: 'Map Box' }, { id: 'googleMap', name: 'Google Maps' }],
    label_FirstName: 'First Name',
    label_Contact: 'Phone',
    label_Email: 'Email',
    label_LastName: 'Last Name',
    label_Image: 'Avatar',
    label_Role: 'Role',
    label_Department: 'Account',
    _id: '_id',
    email: 'email',
    name: 'name',
    lastname: 'lastname',
    img: 'img',
    type: 'type',
    phone: 'phone',
    admins: 'admins',
    required_Name: 'First Name  required',
    required_lastName:'Last Name  required',
    required_Phone: 'Phone Number required',
    required_Email: 'Email  required',
    validation_Phone_MinL: 'Phone Number required atleast 10 characters',
    validation_Phone_MaxL: 'Phone Number required only 12 characters',
    validation_Email: 'Email must be a valid email address',
    accountReqMsg:'Account Required',
    adminReqMsg:'Admin Required',
    privilegeTitle : 'Privileges',
    typeLabel :'Administrator Type',
    accountAdminLabel:'Admin',
    accountAdmin: 'adminId',
    organisationName:'organisationName',
    label_orgname:'Name',
    label_logo:'Logo',
    autoApproveDevice:'autoApproveDevice',
    label_autoApprove:'Auto-Approve Devices',
    tabs:{admins:'Administrator',
    forms: 'Formsz',
    projects: 'Projects',
    tasks: 'Tasks',
    templates: 'Templates',
    users: 'Users',
    workflow: 'Work Flows',
    downloads : 'Downloads',
    devices : 'Device Management',
    category :' Categories',
    approvals:'Approvals',
    location:'Map Location'
    },
    selectDatatable:'Select ReferenceList',
    collectionName:'collectionName',
    dropdownNameLabel:'Reference list Name',
    uploadSheet:'Upload Excel Data',
    xlsxformat: 'Please attach xlsx formatted file only',
    options:'options',
    edit:'edit',
    create:'create',
    collectionNameRequired:'Name Required',
    accountLock:'accountLock',
    lockInterval:'lockInterval',
    maxFilesAllowedPerRecord:'maxFilesAllowedPerRecord',
    maxSizeOfEachFileAllowedPerRecord:'maxSizeOfEachFileAllowedPerRecord',
    accountLockLabel:'Account Lock',
    lockIntervalLabel:'Lock Interval',
    parameter : 'Parameter',
    value : 'Value',
    Description : 'Description',
    accountDescription  : 'Number of attempts after which account will be locked',
    intervalDescription:'Minimum of time locked after 5 unsuccessful attempts',
    filesDescription:'Maximum number of files allowed per record',
    sizeDescription:'Maximum size of each file allowed per record',
    isAccountLockEnabled:'Account Lock',
  }
}
