export class adminConstants {
    public static adminkeys = {
        _id:'_id',
        username:'username',
        email:'email',
        name:'name',
        lastname:'lastname',
        departments:'departments',
        img:'img',
        privilege:'privilege',
        type:'type',
        phone:'phone',
        admins:'admins',
        label_Username :'Username',
        label_FirstName :'First Name',
        label_Contact :'Phone',
        label_Email:'Email',
        label_LastName :'Last Name',
        label_Image:'Select Avatar',
        clearAvatar:'Clear Avatar',
        label_Role:'Role',
        label_DA :'Account Administrator',
        label_GA  :'Group Administrator',
        label_Department:'Account',
        label_Privileges:'Privileges',
        label_Create:'Create',
        label_Update:'Update',
        label_Cancel:'Cancel',
        header_Create:' New Administrator',
        header_Update:'Administrator',
        required_Username:'Username  required',
        required_Name:'First Name  required',
        required_Phone:'Phone Number required',
        required_Email:'Email  required',
        required_LastName:'Last Name  required',
        required_Account:'Account  required',
        validation_Phone_MinL:'Phone Number required atleast 10 characters',
        validation_Phone_MaxL:'Phone Number required only 12 characters',
        validation_Email:'Email must be a valid email address',
        tab2_Content:'Set up your Role and Account',
        tab3_Content:'Set Privileges',

    }
}
