export class dashboardConstansts {
    public static dashboardkeys = {
    selectionButtons:{
                        0:['Usage of System','Account Specific'],
                        1:['Account Specific','Projects','Tasks','Users','Device Management'],
                        3:['Projects','Tasks','Users'],
                        4:['Approvals'],
                        5:['Approvals','Tasks','Users'], 
                        6:['Usage of System','Account Specific','Status of System']   },
    description:{
      'Usage of System':'Provides a high-level Analytics of System Usage',
      'Account Specific':'Provides a high-level Analytics of Accounts',
      'Projects':'Provides a high-level Analytics of Projects',
      'Tasks':'Provides a high-level Analytics of Tasks',
      'Users':'Provides a high-level Analytics of Users',
      'Device Management':'Provides a high-level Analytics of Devices',
      'Status of System':'Provides a high-level Analytics of System Status',
      'Approvals':'Provides a high-level Analytics of Approvals'
    },
    activeLicensesCount:'Active Licenses',
    transactionCount:'Transactions Per Sec',
    DaysForRenewalofLicensesCount:'Renewal Days',
    submittedRecordsCount:'Submitted Records',
    tasksCount:'Tasks',
    projectsCount:'Projects',
    inactiveUsersCount:'Inactive Users',
    activeUsersListArray:'Active Users',
    consumedLicensesList:'Consumed Licenses',
    formsCount:'Forms',
    recordsFeed:'Records Feed',
    username:'Username',
    aName:'Username',
    lastLoggedInTime:'LoggedInTime',
    departments:'Accounts',
    deviceDetails:'Device Details',
    assignedTo:'Name',
    loggedInTime:'LoggedInTime',
    department:'Account',
    statusOfTask:'Task Status',
    completedProjects:'Completed Projects',
    pendingProjectsCount:'Pending Projects',
    workAssignmentCounts:'WorkAssignments',
    totalprojects:'Projects',
    workAssignments:'WorkAssignments',
    activeUsersCount:'Active Users',
    userCount:'Users',
    activeUserList:'Active UserList',
    completedTasks:'Completed Tasks',
    pendingTasksCount:'Pending Tasks',
    accountsCount:'Accounts',
    pendingDevicesCount:'Pending Devices',
    totalDevices:'Devices',
    dbSize:'DB Size(MB)',
    deviceCount :'Devices',
    logFileSize:'LogFileSize(MB)',
    middleWareServers:'MiddleWare Servers',
    accountspecific:'admins',
    projects:'projects',
    tasks :'tasks',
    users:'users',
    devicemanagement:'devices',
    approvals:'approvals',
    Completed:'Completed',
    'workflow Cycle Started':'Workflow Cycle Started',
    New:'New',
    androidDevicesCount:'Android Devices',
    macDevicesCount:'Mac Devices',
    pendingTasks:'Pending Tasks',
    endDate:'End Date',
    startDate:'Start Date',
    name:'Task Name',
    projectTasksCount:'Tasks Count',
    apName:'Project Name',
    completedProjectsList:'Completed ProjectsList',
    lockedAccountUser:'Locked Users',
    accountLockedOn:"Account LockedOn",
    
  }
  }
  