export class Devicemanagementconstants  {
  public static devicekeys = {
  startDate: 'fromdate',
  endDate: 'todate',
  tableFeilds : ['#', 'Manufacturer', 'Model', 'Platform', 'Version', 'App Version', 'MAC Address', 'UUID', 'Username', 'Status', 'Action'],
  deviceStatusList : ['All', 'Approved', 'Pending', 'Rejected', 'Suspended', 'Unauthorized'],
  tableActivityFeilds : ['#', 'Device Name', 'Action', 'Device Id', 'Date', 'Time'],
  deviceDeleteMessage : 'Do you want to Delete Device',
  approve: 'Approve',
  reject: 'Reject',
  suspende: 'Suspend',
  pending: 'Pending',
  revoke: 'Revoke',
  unauthorize: 'Unauthorize',
  approved: 'Approved',
  rejected: 'Rejected',
  suspended: 'Suspended',
  revoked: 'Revoked',
  unauthorized: 'Unauthorized',
  all: 'All',
  errorMsg: 'Something went wrong!',
  cancelMsg: 'Device Delete Action is Cancelled',
  successMsg: 'success',
  failedMsg: 'Failed',
  departments: 'departments',
  todateRequired: 'To Date is required',
  fromdateRequired: 'From Date is required',
  };
}
